spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mariadb://localhost:3306/mudi
#spring.datasource.username=mudi
#spring.datasource.password=mudi

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.readiness.tcp.connect-timeout=20s

spring.devtools.restart.enabled=true

spring.jpa.open-in-view=true

spring.thymeleaf.cache=false

server.servlet.context-path=/mudi