CREATE TABLE USERS(
	ID BIGINT NOT NULL UNSIGNED,
	USERNAME VARCHAR NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	ENABLED BIT(1) DEFAULT 1,
	CONSTRAINT PK_USERNAME PRIMARY KEY(ID),
	CONSTRAINT UN_USERNAME UNIQUE(USERNAME)
);

CREATE TABLE PEDIDOS(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR NOT NULL,
	VALOR DECIMAL NOT NULL UNSIGNED,
	DATA_ENTREGA DATE NOT NULL,
	URL_PRODUTO TEXT NOT NULL,
	URL_IMAGEM TEXT NOT NULL,
	DESCRICAO TEXT NOT NULL,
	STATUS VARCHAR NOT NULL,
	USER_ID BIGINT NOT NULL,
	CONSTRAINT PK_PEDIDO_ID PRIMARY KEY(ID),
	CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE OFERTAS(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	VALOR DECIMAL NOT NULL UNSIGNED,
	DATA_ENTREGA DATE NOT NULL,
	COMENTARIO TEXT NULL,
	PEDIDO_ID BIGINT NOT NULL UNSIGNED,
	CONSTRAINT PK_OFERTA_ID PRIMARY KEY(ID),
	CONSTRAINT FK_PEDIDO_ID FOREIGN KEY(PEDIDO_ID) REFERENCES PEDIDOS(ID)
);